import type { Locale } from "./i18n";
const en = {
  title: "Installed apps",
  subtitle: "Find what takes up space. Review each app before removing it.",
  installed: "Installed programs",
  large: "Large apps",
  recent: "Added recently",
  largeHint: "500 MB or more",
  recentHint: "Last 30 days",
  refresh: "Refresh inventory",
  filters: "Filters & display",
  lastScan: "Updated",
  checkUpdates: "Check for updates",
  checking: "Checking for updates…",
  upToDate: "You're up to date",
  checkFailed: "Couldn't check. Try again when you're online.",
  unknownProgress: "Downloading update…",
  busy: "Finish the current removal before updating.",
  until: "Pro until",
  close: "Close",
  accountHint: "Account, subscription and preferences",
  viewDetails: "Review details",
};
export const workspaceCopy: Record<Locale, typeof en> = {
  en,
  it: {
    title: "App installate",
    subtitle: "Scopri cosa occupa spazio. Controlla ogni app prima di rimuoverla.",
    installed: "Programmi installati",
    large: "App più grandi",
    recent: "Aggiunte di recente",
    largeHint: "Almeno 500 MB",
    recentHint: "Ultimi 30 giorni",
    refresh: "Aggiorna elenco",
    filters: "Filtri e visualizzazione",
    lastScan: "Aggiornato",
    checkUpdates: "Cerca aggiornamenti",
    checking: "Ricerca aggiornamenti…",
    upToDate: "Hai la versione più recente",
    checkFailed: "Verifica non riuscita. Riprova quando sei online.",
    unknownProgress: "Download aggiornamento…",
    busy: "Completa la rimozione prima di aggiornare.",
    until: "Pro fino al",
    close: "Chiudi",
    accountHint: "Account, abbonamento e preferenze",
    viewDetails: "Esamina dettagli",
  },
  fr: {
    title: "Applications installées",
    subtitle:
      "Repérez ce qui occupe de l’espace. Examinez chaque application avant de la supprimer.",
    installed: "Programmes installés",
    large: "Applications volumineuses",
    recent: "Ajouts récents",
    largeHint: "500 Mo ou plus",
    recentHint: "30 derniers jours",
    refresh: "Actualiser la liste",
    filters: "Filtres et affichage",
    lastScan: "Actualisé",
    checkUpdates: "Rechercher une mise à jour",
    checking: "Recherche en cours…",
    upToDate: "Vous êtes à jour",
    checkFailed: "Vérification impossible. Réessayez en ligne.",
    unknownProgress: "Téléchargement…",
    busy: "Terminez la suppression avant la mise à jour.",
    until: "Pro jusqu’au",
    close: "Fermer",
    accountHint: "Compte, abonnement et préférences",
    viewDetails: "Voir les détails",
  },
  es: {
    title: "Aplicaciones instaladas",
    subtitle: "Descubre qué ocupa espacio. Revisa cada aplicación antes de eliminarla.",
    installed: "Programas instalados",
    large: "Aplicaciones grandes",
    recent: "Añadidas recientemente",
    largeHint: "500 MB o más",
    recentHint: "Últimos 30 días",
    refresh: "Actualizar lista",
    filters: "Filtros y visualización",
    lastScan: "Actualizado",
    checkUpdates: "Buscar actualizaciones",
    checking: "Buscando actualizaciones…",
    upToDate: "Tienes la última versión",
    checkFailed: "No se pudo comprobar. Inténtalo cuando tengas conexión.",
    unknownProgress: "Descargando actualización…",
    busy: "Termina la desinstalación antes de actualizar.",
    until: "Pro hasta",
    close: "Cerrar",
    accountHint: "Cuenta, suscripción y preferencias",
    viewDetails: "Revisar detalles",
  },
  de: {
    title: "Installierte Apps",
    subtitle: "Finde heraus, was Speicher belegt. Prüfe jede App vor dem Entfernen.",
    installed: "Installierte Programme",
    large: "Große Apps",
    recent: "Kürzlich hinzugefügt",
    largeHint: "Mindestens 500 MB",
    recentHint: "Letzte 30 Tage",
    refresh: "Liste aktualisieren",
    filters: "Filter und Anzeige",
    lastScan: "Aktualisiert",
    checkUpdates: "Nach Updates suchen",
    checking: "Suche nach Updates…",
    upToDate: "Du bist auf dem neuesten Stand",
    checkFailed: "Prüfung fehlgeschlagen. Versuche es erneut, wenn du online bist.",
    unknownProgress: "Update wird geladen…",
    busy: "Beende die Deinstallation vor dem Update.",
    until: "Pro bis",
    close: "Schließen",
    accountHint: "Konto, Abonnement und Einstellungen",
    viewDetails: "Details prüfen",
  },
};
