import type { Locale } from "./i18n";
const en = {
  title: "Installed apps",
  subtitle: "Find what takes up space. Review each app before removing it.",
  installed: "Installed programs",
  large: "Large apps",
  recent: "Added recently",
  largeHint: "500 MB or more",
  recentHint: "Last 30 days",
  freed: "Freed so far",
  freedHint: (count: number) => `${String(count)} verified removals`,
  refresh: "Refresh inventory",
  filters: "Filters & display",
  lastScan: "Updated",
  checkUpdates: "Check for updates",
  checking: "Checking for updates…",
  upToDate: "You're up to date",
  checkFailed: "Couldn't check. Try again when you're online.",
  unknownProgress: "Downloading update…",
  busy: "Finish the current removal before updating.",
  until: "Pro until",
  close: "Close",
  accountHint: "Account, subscription and preferences",
  viewDetails: "Details",
  clearHistory: "Clear history",
  clearHistoryTitle: "Clear removal history?",
  clearHistoryBody:
    "Deletes local receipts and recovery details for removed entries. Installed apps, restore points and exports stay unchanged.",
  cancel: "Cancel",
  clearingHistory: "Clearing…",
};
export const workspaceCopy: Record<Locale, typeof en> = {
  en,
  it: {
    title: "App installate",
    subtitle: "Scopri cosa occupa spazio. Controlla ogni app prima di rimuoverla.",
    installed: "Programmi installati",
    large: "App più grandi",
    recent: "Aggiunte di recente",
    largeHint: "Almeno 500 MB",
    recentHint: "Ultimi 30 giorni",
    freed: "Liberati finora",
    freedHint: (count) => `${String(count)} rimozioni verificate`,
    refresh: "Aggiorna elenco",
    filters: "Filtri e visualizzazione",
    lastScan: "Aggiornato",
    checkUpdates: "Cerca aggiornamenti",
    checking: "Ricerca aggiornamenti…",
    upToDate: "Hai la versione più recente",
    checkFailed: "Verifica non riuscita. Riprova quando sei online.",
    unknownProgress: "Download aggiornamento…",
    busy: "Completa la rimozione prima di aggiornare.",
    until: "Pro fino al",
    close: "Chiudi",
    accountHint: "Account, abbonamento e preferenze",
    viewDetails: "Dettagli",
    clearHistory: "Svuota cronologia",
    clearHistoryTitle: "Svuotare la cronologia?",
    clearHistoryBody:
      "Elimina ricevute locali e dettagli di recupero delle voci rimosse. App, punti di ripristino ed esportazioni restano invariati.",
    cancel: "Annulla",
    clearingHistory: "Cancellazione…",
  },
  fr: {
    title: "Applications installées",
    subtitle:
      "Repérez ce qui occupe de l’espace. Examinez chaque application avant de la supprimer.",
    installed: "Programmes installés",
    large: "Applications volumineuses",
    recent: "Ajouts récents",
    largeHint: "500 Mo ou plus",
    recentHint: "30 derniers jours",
    freed: "Libérés à ce jour",
    freedHint: (count) => `${String(count)} suppressions vérifiées`,
    refresh: "Actualiser la liste",
    filters: "Filtres et affichage",
    lastScan: "Actualisé",
    checkUpdates: "Rechercher une mise à jour",
    checking: "Recherche en cours…",
    upToDate: "Vous êtes à jour",
    checkFailed: "Vérification impossible. Réessayez en ligne.",
    unknownProgress: "Téléchargement…",
    busy: "Terminez la suppression avant la mise à jour.",
    until: "Pro jusqu’au",
    close: "Fermer",
    accountHint: "Compte, abonnement et préférences",
    viewDetails: "Détails",
    clearHistory: "Effacer l’historique",
    clearHistoryTitle: "Effacer l’historique ?",
    clearHistoryBody:
      "Efface les reçus locaux et détails de récupération. Les applications, points de restauration et exports restent inchangés.",
    cancel: "Annuler",
    clearingHistory: "Suppression…",
  },
  es: {
    title: "Aplicaciones instaladas",
    subtitle: "Descubre qué ocupa espacio. Revisa cada aplicación antes de eliminarla.",
    installed: "Programas instalados",
    large: "Aplicaciones grandes",
    recent: "Añadidas recientemente",
    largeHint: "500 MB o más",
    recentHint: "Últimos 30 días",
    freed: "Liberados hasta ahora",
    freedHint: (count) => `${String(count)} eliminaciones verificadas`,
    refresh: "Actualizar lista",
    filters: "Filtros y visualización",
    lastScan: "Actualizado",
    checkUpdates: "Buscar actualizaciones",
    checking: "Buscando actualizaciones…",
    upToDate: "Tienes la última versión",
    checkFailed: "No se pudo comprobar. Inténtalo cuando tengas conexión.",
    unknownProgress: "Descargando actualización…",
    busy: "Termina la desinstalación antes de actualizar.",
    until: "Pro hasta",
    close: "Cerrar",
    accountHint: "Cuenta, suscripción y preferencias",
    viewDetails: "Detalles",
    clearHistory: "Borrar historial",
    clearHistoryTitle: "¿Borrar el historial?",
    clearHistoryBody:
      "Elimina recibos locales y detalles de recuperación. Las aplicaciones, los puntos de restauración y las exportaciones no cambian.",
    cancel: "Cancelar",
    clearingHistory: "Borrando…",
  },
  de: {
    title: "Installierte Apps",
    subtitle: "Finde heraus, was Speicher belegt. Prüfe jede App vor dem Entfernen.",
    installed: "Installierte Programme",
    large: "Große Apps",
    recent: "Kürzlich hinzugefügt",
    largeHint: "Mindestens 500 MB",
    recentHint: "Letzte 30 Tage",
    freed: "Bisher freigegeben",
    freedHint: (count) => `${String(count)} geprüfte Entfernungen`,
    refresh: "Liste aktualisieren",
    filters: "Filter und Anzeige",
    lastScan: "Aktualisiert",
    checkUpdates: "Nach Updates suchen",
    checking: "Suche nach Updates…",
    upToDate: "Du bist auf dem neuesten Stand",
    checkFailed: "Prüfung fehlgeschlagen. Versuche es erneut, wenn du online bist.",
    unknownProgress: "Update wird geladen…",
    busy: "Beende die Deinstallation vor dem Update.",
    until: "Pro bis",
    close: "Schließen",
    accountHint: "Konto, Abonnement und Einstellungen",
    viewDetails: "Details",
    clearHistory: "Verlauf löschen",
    clearHistoryTitle: "Verlauf löschen?",
    clearHistoryBody:
      "Löscht lokale Belege und Wiederherstellungsdetails. Apps, Wiederherstellungspunkte und Exporte bleiben unverändert.",
    cancel: "Abbrechen",
    clearingHistory: "Wird gelöscht…",
  },
  pt: {
    title: "Aplicações instaladas",
    subtitle: "Descubra o que ocupa espaço. Reveja cada aplicação antes de a remover.",
    installed: "Programas instalados",
    large: "Aplicações grandes",
    recent: "Adicionadas recentemente",
    largeHint: "500 MB ou mais",
    recentHint: "Últimos 30 dias",
    freed: "Libertado até agora",
    freedHint: (count) => `${String(count)} remoções verificadas`,
    refresh: "Atualizar lista",
    filters: "Filtros e apresentação",
    lastScan: "Atualizado",
    checkUpdates: "Procurar atualizações",
    checking: "A procurar atualizações…",
    upToDate: "Tem a versão mais recente",
    checkFailed: "Não foi possível verificar. Tente novamente quando estiver online.",
    unknownProgress: "A transferir a atualização…",
    busy: "Conclua a remoção atual antes de atualizar.",
    until: "Pro até",
    close: "Fechar",
    accountHint: "Conta, subscrição e preferências",
    viewDetails: "Detalhes",
    clearHistory: "Limpar histórico",
    clearHistoryTitle: "Limpar o histórico de remoções?",
    clearHistoryBody:
      "Apaga os recibos locais e os detalhes de recuperação das entradas removidas. As aplicações instaladas, os pontos de restauro e as exportações não são alterados.",
    cancel: "Cancelar",
    clearingHistory: "A limpar…",
  },
};
